version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - conf.env
        ports:
            - "8000:8000"
        runtime: nvidia
        volumes:
            - ./:/sukima/
            - /opt/cuda:/usr/local/cuda
        command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
        depends_on:
            - database
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [ gpu ]


    database:
        image: postgres:14-bullseye
        env_file:
            - conf.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
